# Builds templates/included-vc-report-data-template.xlsx from data-templates/*.csv
# Usage: python3 scripts/build_data_template.py templates/included-vc-report-data-template.xlsx
import csv, datetime, sys
from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.comments import Comment
from openpyxl.worksheet.datavalidation import DataValidation
from openpyxl.utils import get_column_letter

SRC = 'data-templates'
OUT = sys.argv[1]
FEATURED = {'fellow-alexandra-smith', 'fellow-daniel-mensah', 'fellow-amara-okafor'}
FIRMS = {'firm-example-capital', 'firm-horizon-ventures'}

KELLY = '128A38'; INK = '111111'; PAPER = 'FAFAF8'; LIME = 'F0FADF'; GOLD = 'FFF6DB'; GREY = '5C5C5C'
F = lambda **k: Font(name='Arial', **k)
thin = Side(style='thin', color='E5E5E5')

# (tab, file, [(column, required, kind, help)])
# kind: text | date | yesno | int | num | longtext | enum:<a,b> | ref:<tab>
TABLES = [
 ('cohorts', 'One row per programme cohort.', [
   ('cohort_id', 1, 'text', 'Short stable ID you choose, e.g. cohort-2026. Used to link everything else.'),
   ('cohort_name', 1, 'text', 'Shown on reports, e.g. Investment Cohort 2026'),
   ('programme_name', 1, 'text', 'Used in report sentences, e.g. Investment Cohort'),
   ('start_date', 1, 'date', 'First session date'),
   ('end_date', 1, 'date', 'Last session date')]),
 ('firms', 'One row per participating investment firm. Each firm gets one private company report.', [
   ('firm_id', 1, 'text', 'Short stable ID you choose, e.g. firm-example-capital. Never change it once used.'),
   ('firm_name', 1, 'text', 'As it should appear in the report'),
   ('cohort_id', 1, 'ref:cohorts', 'Pick from the cohorts tab'),
   ('logo_url', 0, 'text', 'Link to the firm logo (PNG or SVG). Optional; we can also collect logos separately.'),
   ('report_token', 0, 'text', 'Leave blank. The system generates the private link code; paste it back here afterwards so links stay the same.'),
   ('report_enabled', 0, 'yesno', 'yes = firm receives a report (default). no = fellows only count towards cohort averages.')]),
 ('fellows', 'One row per sponsored fellow. Include every fellow in the cohort, even from firms not receiving a report, so cohort averages are correct.', [
   ('fellow_id', 1, 'text', 'Short stable ID you choose, e.g. fellow-alexandra-smith'),
   ('first_name', 1, 'text', ''),
   ('last_name', 1, 'text', ''),
   ('role', 0, 'text', 'Job title, shown under the name'),
   ('firm_id', 1, 'ref:firms', 'Pick from the firms tab'),
   ('cohort_id', 1, 'ref:cohorts', 'Pick from the cohorts tab'),
   ('report_token', 0, 'text', 'Leave blank; generated by the system.')]),
 ('sessions', 'One row per programme session, including sessions not yet held.', [
   ('session_id', 1, 'text', 'Short stable ID, e.g. s01'),
   ('cohort_id', 1, 'ref:cohorts', ''),
   ('session_number', 1, 'int', '1, 2, 3 ...'),
   ('session_title', 1, 'text', 'As it should appear in the report'),
   ('session_date', 1, 'date', ''),
   ('status', 0, 'enum:held,scheduled,cancelled', 'held / scheduled / cancelled. Cancelled sessions are left out of all figures.'),
   ('facilitator', 0, 'text', 'Optional')]),
 ('attendance_feedback', 'One row per fellow per session held. Paste reflections exactly as the fellow wrote them; they are shown word for word.', [
   ('fellow_id', 1, 'ref:fellows', 'Pick from the fellows tab'),
   ('session_id', 1, 'ref:sessions', 'Pick from the sessions tab'),
   ('attended', 1, 'yesno', 'yes / no'),
   ('feedback_submitted', 1, 'yesno', 'yes / no. Only counts when attended = yes.'),
   ('what_i_learned', 0, 'longtext', 'Original response to "What did you learn?" — copy exactly, do not edit'),
   ('what_ill_apply', 0, 'longtext', 'Original response to "What will you apply?" — copy exactly, do not edit'),
   ('feedback_submitted_at', 0, 'date', 'Optional')]),
 ('capstone', 'Add a NEW row each time a fellow\'s Capstone status changes (do not overwrite), so earlier reports stay as issued.', [
   ('fellow_id', 1, 'ref:fellows', ''),
   ('recorded_at', 1, 'date', 'The date this row became true'),
   ('submitted', 1, 'yesno', 'yes / no'),
   ('submission_date', 0, 'date', 'Date received'),
   ('submission_deadline', 1, 'date', ''),
   ('submitted_on_time', 0, 'yesno', 'Leave blank to work it out from the two dates'),
   ('assessment_status', 1, 'enum:not_started,pending,complete', 'Score and feedback are only shown when complete'),
   ('assessment_score', 0, 'num', 'Leave blank until assessed'),
   ('assessment_max_score', 0, 'num', 'Default 100'),
   ('detailed_feedback', 0, 'longtext', 'Assessor\'s written feedback, shown in full when complete')]),
 ('checkpoints', 'One row per progress report round. A checkpoint fixes which sessions that report covers.', [
   ('checkpoint_id', 1, 'text', 'e.g. cp-2026-1'),
   ('cohort_id', 1, 'ref:cohorts', ''),
   ('checkpoint_title', 1, 'text', 'e.g. Checkpoint 1'),
   ('reporting_date', 1, 'date', 'Data as at this date'),
   ('session_ids', 1, 'text', 'Sessions covered, separated by semicolons: s01;s02;s03'),
   ('status', 0, 'enum:draft,published', 'draft = admin preview only. published = firms can see it.')]),
 ('authorised_users', 'Who may open each firm\'s report.', [
   ('user_id', 1, 'text', 'Any unique ID, e.g. u1'),
   ('email', 1, 'text', 'The email they will sign in with'),
   ('name', 0, 'text', ''),
   ('firm_id', 0, 'ref:firms', 'Their firm. Leave blank for Included VC staff.'),
   ('role', 1, 'enum:firm_leader,admin', 'firm_leader = sees their firm only. admin = Included VC team.'),
   ('access_status', 0, 'enum:active,invited,revoked', 'revoked removes access')]),
]

def rows(tab):
    with open(f'{SRC}/{tab}.csv', newline='', encoding='utf-8') as f:
        r = list(csv.DictReader(f))
    keep = {
        'firms': lambda x: x['firm_id'] in FIRMS,
        'fellows': lambda x: x['fellow_id'] in FEATURED,
        'attendance_feedback': lambda x: x['fellow_id'] in FEATURED,
        'capstone': lambda x: x['fellow_id'] in FEATURED,
    }.get(tab, lambda x: True)
    return [x for x in r if keep(x)]

wb = Workbook()
start = wb.active; start.title = 'Start here'

def todate(v):
    return datetime.datetime.strptime(v, '%Y-%m-%d') if v else None

for tab, desc, cols in TABLES:
    ws = wb.create_sheet(tab)
    ws.sheet_properties.tabColor = KELLY if tab != 'authorised_users' else GREY
    for i, (name, req, kind, helptext) in enumerate(cols, 1):
        c = ws.cell(row=1, column=i, value=name)
        c.font = F(bold=True, color='FFFFFF' if req else INK, size=10)
        c.fill = PatternFill('solid', fgColor=KELLY if req else 'E5E5E5')
        c.alignment = Alignment(vertical='center')
        c.comment = Comment(('REQUIRED. ' if req else 'Optional. ') + helptext, 'Included VC')
        width = 60 if kind == 'longtext' else 14 if kind in ('date', 'yesno', 'int', 'num') else max(16, len(name) + 4)
        if name in ('session_title', 'firm_name', 'email', 'logo_url', 'session_ids'): width = 36
        ws.column_dimensions[get_column_letter(i)].width = width
        col = get_column_letter(i)
        rng = f'{col}2:{col}2000'
        dv = None
        if kind == 'yesno':
            dv = DataValidation(type='list', formula1='"yes,no"', allow_blank=True)
        elif kind.startswith('enum:'):
            dv = DataValidation(type='list', formula1='"' + kind[5:] + '"', allow_blank=True)
        elif kind.startswith('ref:'):
            dv = DataValidation(type='list', formula1=f"{kind[4:]}!$A$2:$A$2000", allow_blank=True)
        elif kind == 'date':
            dv = DataValidation(type='date', operator='greaterThan', formula1='DATE(2020,1,1)', allow_blank=True)
            dv.error = 'Enter a date, e.g. 2026-08-17'
        if dv:
            dv.showErrorMessage = True
            ws.add_data_validation(dv); dv.add(rng)
        if kind == 'date':
            for r in range(2, 2001): ws.cell(row=r, column=i).number_format = 'yyyy-mm-dd'
        if kind == 'longtext':
            for r in range(2, 2001): ws.cell(row=r, column=i).alignment = Alignment(wrap_text=True, vertical='top')
    ws.freeze_panes = 'A2'
    ws.row_dimensions[1].height = 22
    for r, rec in enumerate(rows(tab), 2):
        for i, (name, req, kind, _) in enumerate(cols, 1):
            v = rec.get(name, '')
            if name == 'facilitator' and 'demo' in v: v = ''
            if name == 'report_token': v = ''
            if kind == 'date': v = todate(v)
            elif kind in ('int', 'num') and v != '': v = float(v) if '.' in v else int(v)
            elif v == '': v = None
            c = ws.cell(row=r, column=i, value=v)
            c.font = F(size=10, italic=True, color='8A8A8A')
            if kind == 'date': c.number_format = 'yyyy-mm-dd'
            if kind == 'longtext': c.alignment = Alignment(wrap_text=True, vertical='top')

# ---- Check tab: live figures from the data, for sanity-checking before import
ck = wb.create_sheet('check_figures')
ck.sheet_properties.tabColor = 'FFC400'
ck['A1'] = 'Check figures — calculated from the tabs above. Not imported; for checking only.'
ck['A1'].font = F(bold=True, size=12)
ck['A2'] = 'Counts every session marked "held" and every attendance row, across the whole programme to date. The reports use the same rules per checkpoint.'
ck['A2'].font = F(size=9, color=GREY)
heads = ['fellow_id', 'Name', 'Firm', 'Sessions held', 'Attended', 'Attendance %', 'Feedback submitted', 'Feedback %', 'Missing attendance rows']
for i, h in enumerate(heads, 1):
    c = ck.cell(row=4, column=i, value=h); c.font = F(bold=True, color='FFFFFF', size=10); c.fill = PatternFill('solid', fgColor=INK)
    ck.column_dimensions[get_column_letter(i)].width = [26, 22, 26, 14, 11, 14, 18, 12, 22][i - 1]
N = 300
for k in range(N):
    r = 5 + k; fr = 2 + k
    ck[f'A{r}'] = f'=IF(fellows!A{fr}="","",fellows!A{fr})'
    ck[f'B{r}'] = f'=IF(A{r}="","",fellows!B{fr}&" "&fellows!C{fr})'
    ck[f'C{r}'] = f'=IF(A{r}="","",IFERROR(INDEX(firms!$B$2:$B$2000,MATCH(fellows!E{fr},firms!$A$2:$A$2000,0)),"(unknown firm)"))'
    ck[f'D{r}'] = f'=IF(A{r}="","",COUNTIFS(sessions!$B$2:$B$2000,fellows!F{fr},sessions!$F$2:$F$2000,"held")+COUNTIFS(sessions!$B$2:$B$2000,fellows!F{fr},sessions!$F$2:$F$2000,""))'
    ck[f'E{r}'] = f'=IF(A{r}="","",COUNTIFS(attendance_feedback!$A$2:$A$2000,A{r},attendance_feedback!$C$2:$C$2000,"yes"))'
    ck[f'F{r}'] = f'=IF(A{r}="","",IF(D{r}=0,"—",E{r}/D{r}))'
    ck[f'G{r}'] = f'=IF(A{r}="","",COUNTIFS(attendance_feedback!$A$2:$A$2000,A{r},attendance_feedback!$C$2:$C$2000,"yes",attendance_feedback!$D$2:$D$2000,"yes"))'
    ck[f'H{r}'] = f'=IF(A{r}="","",IF(E{r}=0,"—",G{r}/E{r}))'
    ck[f'I{r}'] = f'=IF(A{r}="","",MAX(0,D{r}-COUNTIFS(attendance_feedback!$A$2:$A$2000,A{r})))'
    for col in 'ABCDEFGHI':
        ck[f'{col}{r}'].font = F(size=10)
    ck[f'F{r}'].number_format = '0%'; ck[f'H{r}'].number_format = '0%'
last = 5 + N - 1
ck['K4'] = 'Cohort averages'; ck['K4'].font = F(bold=True, size=10)
ck['K5'] = 'Attendance'; ck['L5'] = f'=IFERROR(AVERAGE(F5:F{last}),"—")'
ck['K6'] = 'Feedback completion'; ck['L6'] = f'=IFERROR(AVERAGE(H5:H{last}),"—")'
ck['K7'] = 'Average of each fellow\'s rate (fellows with no rate are left out).'
for c in ('K5', 'K6', 'L5', 'L6'): ck[c].font = F(size=10)
ck['K7'].font = F(size=9, color=GREY)
ck['L5'].number_format = '0%'; ck['L6'].number_format = '0%'
ck.column_dimensions['K'].width = 22; ck.column_dimensions['L'].width = 12
ck.freeze_panes = 'A5'

# ---- Start here
s = start
s.sheet_view.showGridLines = False
s.column_dimensions['A'].width = 3; s.column_dimensions['B'].width = 26; s.column_dimensions['C'].width = 92
s['B2'] = 'Investment Cohort progress reports — data template'; s['B2'].font = F(bold=True, size=16)
s['B3'] = 'Fill in one tab per table. Each tab is saved as a CSV (File → Download → CSV, one tab at a time) and uploaded in the report admin.'
s['B3'].font = F(size=10, color=GREY)
row = 5
def line(a, b='', bold=False, fill=None, color=INK):
    global row
    s.cell(row=row, column=2, value=a).font = F(bold=True, size=10, color=color)
    c = s.cell(row=row, column=3, value=b); c.font = F(size=10, bold=bold); c.alignment = Alignment(wrap_text=True, vertical='top')
    if fill:
        s.cell(row=row, column=2).fill = PatternFill('solid', fgColor=fill)
    row += 1

line('HOW TO READ THIS FILE', color=KELLY)
line('Green header', 'Required column. Every row needs a value.', fill=KELLY, color='FFFFFF')
line('Grey header', 'Optional column. Leave blank if you don\'t have it.', fill='E5E5E5')
line('Header notes', 'Hover over any column header to see what goes in it.')
line('Grey italic rows', 'Example rows (the Example Capital / Horizon Ventures demo). Delete them and type your own data over them.')
line('Dropdowns', 'yes/no, status and ID columns have dropdowns, so IDs always match between tabs.')
line('Dates', 'Use real dates. They display as YYYY-MM-DD, which is the format the import expects.')
line('Column names', 'Do not rename, reorder or delete the header row. You may add your own extra columns to the right; they are ignored.')
row += 1
line('FILL IN THIS ORDER', color=KELLY)
for tab, desc, _ in TABLES:
    line(tab, desc)
line('check_figures', 'Not imported. Shows each fellow\'s attendance and feedback figures so you can sanity-check before uploading.')
row += 1
line('RULES THAT MATTER', color=KELLY)
line('IDs', 'Choose short IDs once (e.g. firm-acme, fellow-jane-doe, s01) and never change them. Names can change; IDs cannot.')
line('Every fellow, every session', 'Add one attendance_feedback row for every fellow for every session held, including absences (attended = no). A missing row counts as absent and is flagged.')
line('Reflections', 'Paste the fellow\'s answers exactly as submitted. Nothing is rewritten, summarised or generated by AI; the report shows their own words.')
line('Feedback', 'Feedback only counts for sessions the fellow attended. Feedback completion % = feedback submitted ÷ sessions attended.')
line('Capstone', 'When a status changes (e.g. pending → complete), add a new row with a new recorded_at date instead of editing the old one.')
line('Checkpoints', 'Each report round is a checkpoint listing the sessions it covers. Once published, leave it alone and add the next one.')
line('Cohort averages', 'Include all fellows in the cohort, even if their firm is not receiving a report (set report_enabled = no on that firm).')
line('Links', 'Leave report_token blank. The system creates the private link codes.')
row += 1
line('Questions', 'Full specification: docs/DATA_IMPORT.md in the project repository.')

for ws in wb.worksheets:
    ws.sheet_view.zoomScale = 110
wb.save(OUT)
print('saved', OUT)
